# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audience', '0003_userinfo_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
