# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-04 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audience', '0004_userinfo_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='type',
            field=models.IntegerField(choices=[(2, '\u666e\u901a\u7528\u6237'), (1, '\u7ba1\u7406\u5458')], default=2),
        ),
    ]
