# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('subordinate', models.CharField(max_length=100, null=True)),
                ('image', models.CharField(max_length=255, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('sort_no', models.IntegerField(null=True)),
                ('color_image', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
