# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-01 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color_image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='sort_no',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subordinate',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to=b'images/category/'),
        ),
    ]
