# -*- coding: utf-8 -*-

"""
Django settings for live project.

Generated by 'django-admin startproject' using Django 1.11.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

import sys
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*au6nf39*50(y!uq-r-ivs8dneo5yu$_^b1q21zg*4^jeh+h(j'



# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'raven.contrib.django.raven_compat',
    'rest_framework',
    'public',
    'base',
    'anchor',
    'audience',
    'course',
    'category',
    'management',
    'index',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'live.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'live.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'live',
        'USER': 'root',
        'PASSWORD': 'jihao380',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'


STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'live/static'),
)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_URL = '/management/login/'

# 信信客
XXK_DEV_ID = os.environ.get("XXK_DEV_ID", "8765e76b87d5425e865ed46e68b78abb")
XXK_DEV_KEY = os.environ.get("XXK_DEV_KEY", "fde1264d3b5543e590471059b89f74b9")
XXK_URL = os.environ.get("XXK_URL", "http://www.xinxinke.com/api/send")


# ALIYUN sdk setting
ALIYUN_ACCESS_KEY = os.environ.get("ALIYUN_ACCESS_KEY", "LTAIkTfbZ0KSJKal")
ALIYUN_SECRET = os.environ.get("ALIYUN_SECRET", "W2ajRYEmyAcm94AXmXnOTuMheW46Kg")
if ALIYUN_SECRET[-1] != "&":
    ALIYUN_SECRET = ALIYUN_SECRET + "&"
ALIYUN_API_DOMAIN_LIVE = os.environ.get("ALIYUN_API_DOMAIN_LIVE", "http://live.aliyuncs.com")  # 直播
ALIYUN_API_DOMAIN_VOD = os.environ.get("ALIYUN_API_DOMAIN_VOD", "http://mts.cn-shanghai.aliyuncs.com")  # 点播
ALIYUN_API_DOMAIN_MTS = os.environ.get("ALIYUN_API_DOMAIN_MTS", "http://mts.cn-shanghai.aliyuncs.com")  # 媒体转码

# ALIYUN 直播
ALIYUN_LIVE_PUSH_DOMAIN = os.environ.get("ALIYUN_LIVE_PUSH_DOMAIN", "video-center.alivecdn.com")
ALIYUN_LIVE_CDN_DOMAIN = os.environ.get('ALIYUN_LIVE_CDN_DOMAIN', "live.ilaus.vc")

# # ALIYUN OSS 
# ALIYUN_OSS_ENDPOINT = os.environ.get('ALIYUN_OSS_ENDPOINT', "oss-cn-shanghai.aliyuncs.com")
# ALIYUN_OSS_BUCKET = os.environ.get('ALIYUN_OSS_BUCKET', "ullget-staging")
# ALIYUN_OSS_DIRECTORY_PREFIX = os.environ.get('ALIYUN_OSS_DIRECTORY_PREFIX', "staging/")
# ALIYUN_OSS_CDN_URL = os.environ.get('ALIYUN_OSS_CDN_URL', 'https://stagingcdn.ullget.net/')
# ALIYUN_OSS_REGION = os.environ.get("ALIYUN_OSS_REGION", 'oss-cn-shanghai')

PROJECT_NAME = os.environ.get('PROJECT_NAME', 'ullget')


# ALIYUN 支付
ALIPAY_GATEWAY = "https://openapi.alipay.com/gateway.do"

ALIPAY_PARTNER_ID = os.environ.get("ALIPAY_PARTNER_ID", "2088421705344206")  # PID
ALIPAY_APPID = os.environ.get("ALIPAY_APPID", "2016082201787030")  # 当面付的APPID
