# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-14 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anchor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100, null=True, unique=True, verbose_name='\u8bfe\u7a0bid')),
                ('title', models.CharField(help_text='\u4e0d\u5f97\u8d85\u8fc7100\u5b57\u7b26!', max_length=100, null=True, verbose_name='\u8bfe\u7a0b\u6807\u9898')),
                ('description', models.TextField(verbose_name='\u8bfe\u7a0b\u7b80\u4ecb')),
                ('support', models.IntegerField(default=0, verbose_name='\u70b9\u8d5e')),
                ('against', models.IntegerField(default=0, verbose_name='\u8e29')),
                ('start_time', models.DateTimeField(null=True, verbose_name='\u76f4\u64ad\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.DateTimeField(null=True, verbose_name='\u76f4\u64ad\u7ed3\u675f\u65f6\u95f4')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('up_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('money', models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='\u89c2\u770b\u91d1\u989d')),
                ('sign_num', models.IntegerField(default=0, verbose_name='\u521d\u59cb\u62a5\u540d\u4eba\u6570')),
                ('image', models.CharField(max_length=255, null=True)),
                ('status', models.SmallIntegerField(default=0, verbose_name='\u76f4\u64ad\u72b6\u6001')),
                ('type', models.SmallIntegerField(choices=[(1, '\u76f4\u64ad'), (2, '\u5f55\u64ad')], default=1, verbose_name='\u8bfe\u7a0b\u7c7b\u578b')),
                ('reason', models.CharField(max_length=200, null=True, verbose_name='\u4e0d\u901a\u8fc7\u539f\u56e0')),
                ('url', models.CharField(max_length=500, null=True, verbose_name='\u5730\u5740')),
                ('active', models.IntegerField(default=1, verbose_name='\u6fc0\u6d3b')),
                ('anchor', models.ForeignKey(null=True, on_delete='id', related_name='anchor_video', to='anchor.AnchorInfo', to_field='user_id')),
            ],
            options={
                'db_table': 'video_info',
            },
        ),
    ]
