# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-30 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0008_auto_20170730_0735'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=100, null=True, unique=True, verbose_name='\u8bfe\u7a0bid')),
                ('title', models.CharField(help_text='\u4e0d\u5f97\u8d85\u8fc7100\u5b57\u7b26!', max_length=100, null=True, verbose_name='\u8bfe\u7a0b\u6807\u9898')),
                ('description', models.TextField(verbose_name='\u8bfe\u7a0b\u7b80\u4ecb')),
                ('support', models.IntegerField(default=0, verbose_name='\u70b9\u8d5e')),
                ('against', models.IntegerField(default=0, verbose_name='\u8e29')),
                ('start_time', models.DateTimeField(null=True, verbose_name='\u76f4\u64ad\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.DateTimeField(null=True, verbose_name='\u76f4\u64ad\u7ed3\u675f\u65f6\u95f4')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('up_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('image', models.CharField(max_length=255, null=True)),
                ('status', models.SmallIntegerField(default=0, verbose_name='\u76f4\u64ad\u72b6\u6001')),
                ('audit', models.IntegerField(default=5, verbose_name='\u5ba1\u8ba1\u72b6\u6001')),
                ('reason', models.CharField(max_length=200, null=True, verbose_name='\u4e0d\u901a\u8fc7\u539f\u56e0')),
                ('url', models.CharField(max_length=500, null=True, verbose_name='\u5730\u5740')),
                ('active', models.IntegerField(default=1, verbose_name='\u6fc0\u6d3b')),
                ('anchor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anchor_course', to='anchor.AnchorInfo')),
            ],
            options={
                'db_table': 'course_info',
            },
        ),
        migrations.RemoveField(
            model_name='videoinfo',
            name='anchor',
        ),
        migrations.DeleteModel(
            name='VideoInfo',
        ),
    ]
