# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-01 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20170801_0224'),
        ('course', '0002_auto_20170730_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfo',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Category'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='image',
            field=models.ImageField(null=True, upload_to='images/course/'),
        ),
    ]
