# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-06 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20170801_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfo',
            name='sign_num',
            field=models.IntegerField(default=0, verbose_name='\u521d\u8bc6\u62a5\u540d\u4eba\u6570'),
        ),
    ]
