# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-14 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnchorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, null=True, unique=True)),
                ('name', models.CharField(default='', max_length=30, verbose_name='\u59d3\u540d')),
                ('native', models.CharField(default='', max_length=100, null=True, verbose_name='\u51fa\u751f\u5730')),
                ('sex', models.IntegerField(choices=[(1, '\u7537'), (0, '\u5973')], default=1)),
                ('age', models.IntegerField(default=30, null=True)),
                ('tel', models.CharField(default='', max_length=50, null=True)),
                ('e_mail', models.CharField(default='', max_length=50, null=True)),
                ('title', models.TextField(default='', null=True, verbose_name='\u5934\u8854')),
                ('image', models.CharField(default='', max_length=255, null=True, verbose_name='\u5934\u50cf')),
                ('description', models.TextField(null=True, verbose_name='\u4e2a\u6027\u7b7e\u540d')),
                ('character_name', models.CharField(max_length=100, null=True, unique=True, verbose_name='\u4e2a\u6027\u57df\u540d')),
                ('audit', models.IntegerField(default=5, verbose_name='\u5ba1\u8ba1\u72b6\u6001')),
                ('reason', models.CharField(max_length=300, null=True, verbose_name='\u5ba1\u6279\u5907\u6ce8')),
            ],
            options={
                'db_table': 'anchor_info',
            },
        ),
    ]
