# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchorinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
