# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-30 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0007_auto_20170730_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchorinfo',
            name='image',
            field=models.ImageField(null=True, upload_to='images/anchor/'),
        ),
    ]
